version: 0.2

env:
  variables:
    # Name of the public site
    SITEURL: "https://www.rubegoldberg.io"
#     S3_BUCKET: www.example.com
    DEBIAN_FRONTEND: noninteractive

# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
phases:
  install:
    commands:
      - apt-get update -q
      - apt-get -qq upgrade
      - apt-get -qq install make python3
      - make install
  # pre_build:
  #   commands:
  #     - bin/build pre_build
  build:
    commands:
      - make publish
  post_build:
    commands:
      - aws s3 sync output/ s3://$S3_BUCKET --delete
# artifacts:
#   files:
#     - '**/*'
#   base-directory: output
cache:
  paths:
    - '/root/.virtualenv/pelican/**/*'
